Fix interactive marker problem with gripper
PilzDE/prbt_grippers pull request #5
Opened 2019-04-06 10:17 UTC by hslusarek

This pull request hopefully solves Issue #4.

I looked into this a little bit. [Here](https://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/urdf_srdf/urdf_srdf_tutorial.html#end-effectors) it is stated: "that there are no common links between the end-effector and the parent group it is connected to". Based on this statement and the [pg70.urdf.xacro](https://github.com/PilzDE/prbt_grippers/blob/3bbc438032d2930681ff5282aef541390bab6fb0/prbt_pg70_support/urdf/pg70.urdf.xacro#L35) I changed the parent link to: `"parent_link="${prefix}gripper_finger_left_link"`. This seems to work.

Any objections?

2019-04-09 11:51 UTC, rfeistenauer commented on prbt_pg70_support/config/pg70.srdf.xacro
> +    <end_effector group="gripper" name="pg70_end_effector" parent_link="${prefix}gripper_finger_left_link">
Pretty much every tf but the flange seems to work, so id suggest to rahter use gripper_palm or tcp instead of the left finger link.

2019-04-09 14:12 UTC, jschleicher reviewed
If I open setup-assistant, the documentation says: the specified parent link is used as reference for IK attempts.
![end-effector-setup-assistant](https://user-images.githubusercontent.com/29709205/55806780-3e3f7b80-5ae1-11e9-8d7a-938c477ece1c.png)
Is there IK used for our gripper at all? Did I miss other existing moveit documentation?


Why did you introduce the end-effector-tag in ea840fa? Please add a link to the corresponding lines in `trajectory_generation` for reference. Thanks.

2019-04-10 06:17 UTC, hslusarek commented
> Why did you introduce the end-effector-tag in ea840fa? 

If the end-effector-tag is set, it is possible to check if a JointModelGroup is an end-effector. We use this to rule out that end-effector motions are blended. See [command_list_manager, line 179](https://github.com/PilzDE/pilz_industrial_motion/blob/0fadbcee88aaff65123a8ebc9349fb55057dc1db/pilz_trajectory_generation/src/command_list_manager.cpp#L179) and [tip_frame_getter, line 24](https://github.com/PilzDE/pilz_industrial_motion/blob/0fadbcee88aaff65123a8ebc9349fb55057dc1db/pilz_trajectory_generation/include/pilz_trajectory_generation/tip_frame_getter.h#L24).  

> Is there IK used for our gripper at all? Did I miss other existing moveit documentation?  

As far as I know, we do not use the IK for the Gripper because whenever we  "control/command" the gripper via use a Ptp command which only states joint values as start state. Consequently, no IK calculation is necessary.

> Pretty much every tf but the flange seems to work, so id suggest to rahter use gripper_palm or tcp instead of the left finger link.

For me the concrete parent link does not matter because I only want to know if a JointModelGroup is a End-effector or not (see [command_list_manager, line 179](https://github.com/PilzDE/pilz_industrial_motion/blob/0fadbcee88aaff65123a8ebc9349fb55057dc1db/pilz_trajectory_generation/src/command_list_manager.cpp#L179)). Unfortunately, I need to state the parent frame. Otherwise, I would have just skipped it.

2019-04-10 09:34 UTC, rfeistenauer commented
In this case prbt_tcp seems to be a good link as long as we don't find the need to move it for other reasons.

2019-04-10 09:42 UTC, jschleicher requested changes

2019-04-10 09:42 UTC, jschleicher commented on prbt_pg70_support/config/pg70.srdf.xacro
> +    <end_effector group="gripper" name="pg70_end_effector" parent_link="${prefix}gripper_finger_left_link">
```suggestion
    <end_effector group="gripper" name="pg70_end_effector" parent_link="${prefix}tcp">
```

2019-04-10 10:48 UTC, hslusarek commented
Can we merge?

2019-04-10 10:51 UTC, jschleicher approved these changes

2019-04-10 10:52 UTC, merged